### ISSUE TITLE
Pipeline JSON Validator

### ISSUE THREAD

**Issue by jvasallo** [gogoair/foremast#124]
We should have an intermediary step to check the JSON *before* posting to Spinnaker. On top of that, this enables people to develop plugins to modify pipeline JSON based on business logic (keeping foremast clean). For example, if environment is `dev`, update max ASG size from 3 to 1.

Raw code logic is something like:
```
config_check=True
config_checker=<something>

if config_check:
    json = check_json(config_checker, json_load)
post_spinnaker(json)
```

Cleans up things like #123

**Comment by jvasallo** [comment]
This also enables use to develop cleaner error messages on failed pipeline updates as well.

**Comment by sijis** [comment]
I'm closing this, as I believe its covered by #90.
