### ISSUE TITLE
Remove /13 security restrictions when creating security groups

### ISSUE THREAD

**Issue by sijis** [gogoair/foremast#232]
I'm proposing we remove the following lines of code:
https://github.com/gogoair/foremast/blob/master/src/foremast/securitygroup/create_securitygroup.py#L93-L95

We should not expect external users to have the same restriction we have in our environments.

This will allows users to specify any IP cidr for their security rules.

**Comment by e4r7hbug** [comment]
True, other people probably don't need or want our arbitrary restriction.

**Comment by e4r7hbug** [comment]
Part of me wants to vote on making that a configuration option in case someone does want to use it. This will probably be moved to a Plugin once #231 gets underway if we keep it.

**Comment by sijis** [comment]
We could make it a condition. A concern i have is sprinkling these one-off options into the config. It will make the config large and potentially hard to maintain.
Once plugins are around this is simplified and can be isolated.

@bazimov seems like he would like a warning to be thrown, instead of flat out removing the condition.
I think that's could a good idea and it would be a good compromise.
