### ISSUE TITLE
Specify application name

### ISSUE THREAD

**Issue by kitemongerer** [gogoair/foremast#238]
It would be extremely helpful if there was a way to specify the application name that gets created.

Currently it takes the name by combining the repository name and the group name from git. That means that the repo name and group name combined must be shorter than 24 characters and must only contain alphanumeric characters. This leads to repos with names that are ambiguous and hard to read. 

It seems like a pretty bad flow to have your pipelining tool dictate the names of your repo. If overwriting others' apps is a concern then the group name could be added to the configured name to ensure that only groups can overwrite their apps.

**Comment by ndcampbell** [comment]
This feature does exist in Foremast. It is a flag that can be passed to `create-app` or as env varioable `APPNAME` if using the runner:

```
create-app -h

optional arguments:
  -h, --help         show this help message and exit
  -d, --debug        Set DEBUG output
  -a APP, --app APP  Spinnaker Application name
  --email EMAIL      Email address to associate with application
  --project PROJECT  Git project to associate with application
  --repo REPO        Git repo to associate with application
  --git GIT          Git URI```

While app name can be custom, we feel it is important for organizational consistency with application naming. There are AWS limitations to keep in mind, and consistent naming across all applications makes things like tagging, clean up, and cost allocation much easier. Developers still get to pick their own group and repo names, the tooling does not dictate that as long as they stay with in the limitations.
