### ISSUE TITLE
fix: Check `pyapi-gitlab` returns

### ISSUE THREAD

**Issue by e4r7hbug** [gogoair/foremast#244]
# Problem
Need to check `pyapi-gitlab` returns before trying to use the returned object. For request errors, `False` is returned instead of a more useful object.

There has been some work in https://github.com/pyapi-gitlab/pyapi-gitlab/pull/238 to `raise` instead of return `None`. Switching to handle exceptions would make this a little easier.

# Example:
Should check the return of `.getbranch()` before trying to access like a dict.

```python
# src/foremast/configs/prepare_configs.py
    config_commit = file_lookup.server.getbranch(file_lookup.project_id, 'master')['commit']['id']
```

**Comment by sijis** [comment]
I'm closing this, as we've moved libraries and we do a hard check for `[commit]id` key being available.
https://github.com/gogoair/foremast/blob/master/src/foremast/configs/prepare_configs.py#L41.
