### ISSUE TITLE
feat: Add support for setting Public IP

### ISSUE THREAD

**Issue by e4r7hbug** [gogoair/foremast#59]
Add an option to disable or enable the Public IP allocation. Will need to figure out which values the `"associatePublicIpAddress"` takes in the `stage-deploy.json.j2`.
```json
{
          "associatePublicIpAddress": null
}
```

**Comment by jvasallo** [comment]
Wondering which section to add this too. I think app might make the most sense since thats where we set other things in this category, but this seems to be getting a bit disorganized; keep in app or create `data.ec2`?

I can always add it to app and mark this as a refactor for the future?

**Comment by sijis** [comment]
Maybe we should have a `network` section or part of `asg`, as that has a few network components.

**Comment by e4r7hbug** [comment]
I'm going to put my vote in for `"asg"`. Mainly because the Launch Configuration used by the Auto Scaling Group is what determines the Public IP allocation.
