### ISSUE TITLE
Add IAM requirements to documentation

### ISSUE THREAD

**Issue by sbasgall** [gogoair/foremast#62]
The documentation should include the IAM requirements for foremast to run successfully. 
​
Foremast touches Route 53, Lambda, S3, security groups, IAM, and other AWS services using boto3 outside of Spinnaker's API.

**Comment by ravaan** [comment]
Do you want a detailed documentation introduction to IAM Roles and security groups or just what is required ?

Just want to know what is required and I will start right away

**Comment by e4r7hbug** [comment]
I think @sbasgall wanted an IAM Policy JSON example. This would be the minimal permissions required for foremast to run. Most likely, someone could copy the and paste the JSON into a new Policy.

**Comment by sijis** [comment]
There is some documentation in http://foremast.readthedocs.io/en/latest/infra_assumptions.html#aws which seems to describe what's is needed for run.
Its not a JSON policy or the like, but its helpful in it says what we need.

**Comment by jvasallo** [comment]
Finally fixed this...
https://github.com/gogoair/foremast/pull/293

Sorry for the delay community.
